# Generated by Django 2.2.25 on 2021-12-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
                ('credits', models.IntegerField(default=500)),
                ('alchemyPoints', models.IntegerField(default=100)),
                ('currentTier', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Elements')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
