# Generated by Django 2.2.25 on 2021-12-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='itemId',
            field=models.IntegerField(default=1),
        ),
    ]
