# Generated by Django 2.2.25 on 2021-12-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211215_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='elementId',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='userId',
            field=models.CharField(max_length=16),
        ),
    ]
