# Generated by Django 2.2.25 on 2022-01-20 07:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220120_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='recipes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
